// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/address.dart';
import 'api/engine_ed25519.dart';
import 'api/mpc_engine.dart';
import 'api/simple.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -198266522;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ceres_mpc',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiTypesCurveAsStr({required Curve that});

  Future<Curve> crateApiTypesCurveParse({required String s});

  Future<String> crateApiMpcEngineDecryptBackupShare({
    required String encryptedEnvelope,
    required String userBackupSecret,
  });

  Future<String> crateApiMpcEngineDeriveBackupEnvelope({
    required String localEncryptedShare,
    required String userBackupSecret,
    required String createdAt,
  });

  Future<String> crateApiAddressDeriveEvmAddress({
    required List<int> uncompressedPubkey,
  });

  Future<String> crateApiAddressDeriveSolanaAddress({
    required List<int> verifyingKey,
  });

  Future<String> crateApiMpcEngineExportPrivateKey({
    required String localShare,
    required String serverSharePrivate,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiEngineEd25519Keygen({
    required String sessionId,
    required int round,
    required String serverPayload,
  });

  Future<String> crateApiMpcEngineKeygen({
    required String sessionId,
    required int round,
    required String serverPayload,
  });

  Future<void> crateApiTypesMessageDigestAsBytes({required MessageDigest that});

  Future<MessageDigest> crateApiTypesMessageDigestFromHex({required String s});

  Future<U8Array32> crateApiTypesMessageDigestIntoBytes({
    required MessageDigest that,
  });

  Future<MessageDigest> crateApiTypesMessageDigestNew({
    required U8Array32 bytes,
  });

  Future<String> crateApiEngineEd25519Recover({
    required String sessionId,
    required int round,
    required String serverPayload,
    String? backupShare,
    int? currentRotationVersion,
  });

  Future<String> crateApiMpcEngineRecover({
    required String sessionId,
    required int round,
    required String serverPayload,
    String? backupShare,
    int? currentRotationVersion,
  });

  Future<(Curve, Uint8List)> crateApiTypesShareEnvelopeDecode({
    required String localEncryptedShare,
  });

  Future<String> crateApiTypesShareEnvelopeEncode({
    required ShareEnvelope that,
  });

  Future<ShareEnvelope> crateApiTypesShareEnvelopeNew({
    required Curve curve,
    required List<int> shareBytes,
  });

  Future<String> crateApiEngineEd25519Sign({
    required String sessionId,
    required int round,
    required String serverPayload,
    String? share,
    String? messageHex,
  });

  Future<String> crateApiMpcEngineSign({
    required String sessionId,
    required int round,
    required String serverPayload,
    String? share,
    String? messageHashHex,
  });

  Future<Curve> crateApiTypesWireEnvelopeCurveOrDefault({
    required WireEnvelope that,
  });

  Future<List<Uint8List>> crateApiTypesWireEnvelopeDecodeAllPayloads({
    required WireEnvelope that,
  });

  Future<WireEnvelope> crateApiTypesWireEnvelopeNew({
    required String sessionId,
    required ProtocolType protocol,
    required int round,
    required int fromId,
    int? toId,
    required String payload,
    String? step,
  });

  Future<WireEnvelope> crateApiTypesWireEnvelopeNewBatch({
    required String sessionId,
    required ProtocolType protocol,
    required int round,
    required int fromId,
    int? toId,
    required List<String> payloads,
    String? step,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiTypesCurveAsStr({required Curve that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_curve(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesCurveAsStrConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesCurveAsStrConstMeta =>
      const TaskConstMeta(debugName: "curve_as_str", argNames: ["that"]);

  @override
  Future<Curve> crateApiTypesCurveParse({required String s}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_curve,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTypesCurveParseConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesCurveParseConstMeta =>
      const TaskConstMeta(debugName: "curve_parse", argNames: ["s"]);

  @override
  Future<String> crateApiMpcEngineDecryptBackupShare({
    required String encryptedEnvelope,
    required String userBackupSecret,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(encryptedEnvelope, serializer);
          sse_encode_String(userBackupSecret, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMpcEngineDecryptBackupShareConstMeta,
        argValues: [encryptedEnvelope, userBackupSecret],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMpcEngineDecryptBackupShareConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_backup_share",
        argNames: ["encryptedEnvelope", "userBackupSecret"],
      );

  @override
  Future<String> crateApiMpcEngineDeriveBackupEnvelope({
    required String localEncryptedShare,
    required String userBackupSecret,
    required String createdAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(localEncryptedShare, serializer);
          sse_encode_String(userBackupSecret, serializer);
          sse_encode_String(createdAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMpcEngineDeriveBackupEnvelopeConstMeta,
        argValues: [localEncryptedShare, userBackupSecret, createdAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMpcEngineDeriveBackupEnvelopeConstMeta =>
      const TaskConstMeta(
        debugName: "derive_backup_envelope",
        argNames: ["localEncryptedShare", "userBackupSecret", "createdAt"],
      );

  @override
  Future<String> crateApiAddressDeriveEvmAddress({
    required List<int> uncompressedPubkey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(uncompressedPubkey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAddressDeriveEvmAddressConstMeta,
        argValues: [uncompressedPubkey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddressDeriveEvmAddressConstMeta =>
      const TaskConstMeta(
        debugName: "derive_evm_address",
        argNames: ["uncompressedPubkey"],
      );

  @override
  Future<String> crateApiAddressDeriveSolanaAddress({
    required List<int> verifyingKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(verifyingKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAddressDeriveSolanaAddressConstMeta,
        argValues: [verifyingKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddressDeriveSolanaAddressConstMeta =>
      const TaskConstMeta(
        debugName: "derive_solana_address",
        argNames: ["verifyingKey"],
      );

  @override
  Future<String> crateApiMpcEngineExportPrivateKey({
    required String localShare,
    required String serverSharePrivate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(localShare, serializer);
          sse_encode_String(serverSharePrivate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMpcEngineExportPrivateKeyConstMeta,
        argValues: [localShare, serverSharePrivate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMpcEngineExportPrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "export_private_key",
        argNames: ["localShare", "serverSharePrivate"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiEngineEd25519Keygen({
    required String sessionId,
    required int round,
    required String serverPayload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_i_32(round, serializer);
          sse_encode_String(serverPayload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEngineEd25519KeygenConstMeta,
        argValues: [sessionId, round, serverPayload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEd25519KeygenConstMeta =>
      const TaskConstMeta(
        debugName: "keygen",
        argNames: ["sessionId", "round", "serverPayload"],
      );

  @override
  Future<String> crateApiMpcEngineKeygen({
    required String sessionId,
    required int round,
    required String serverPayload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_i_32(round, serializer);
          sse_encode_String(serverPayload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMpcEngineKeygenConstMeta,
        argValues: [sessionId, round, serverPayload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMpcEngineKeygenConstMeta => const TaskConstMeta(
    debugName: "keygen",
    argNames: ["sessionId", "round", "serverPayload"],
  );

  @override
  Future<void> crateApiTypesMessageDigestAsBytes({
    required MessageDigest that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_message_digest(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesMessageDigestAsBytesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesMessageDigestAsBytesConstMeta =>
      const TaskConstMeta(
        debugName: "message_digest_as_bytes",
        argNames: ["that"],
      );

  @override
  Future<MessageDigest> crateApiTypesMessageDigestFromHex({required String s}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_digest,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTypesMessageDigestFromHexConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesMessageDigestFromHexConstMeta =>
      const TaskConstMeta(
        debugName: "message_digest_from_hex",
        argNames: ["s"],
      );

  @override
  Future<U8Array32> crateApiTypesMessageDigestIntoBytes({
    required MessageDigest that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_message_digest(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesMessageDigestIntoBytesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesMessageDigestIntoBytesConstMeta =>
      const TaskConstMeta(
        debugName: "message_digest_into_bytes",
        argNames: ["that"],
      );

  @override
  Future<MessageDigest> crateApiTypesMessageDigestNew({
    required U8Array32 bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8_array_32(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_message_digest,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesMessageDigestNewConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesMessageDigestNewConstMeta =>
      const TaskConstMeta(debugName: "message_digest_new", argNames: ["bytes"]);

  @override
  Future<String> crateApiEngineEd25519Recover({
    required String sessionId,
    required int round,
    required String serverPayload,
    String? backupShare,
    int? currentRotationVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_i_32(round, serializer);
          sse_encode_String(serverPayload, serializer);
          sse_encode_opt_String(backupShare, serializer);
          sse_encode_opt_box_autoadd_i_32(currentRotationVersion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEngineEd25519RecoverConstMeta,
        argValues: [
          sessionId,
          round,
          serverPayload,
          backupShare,
          currentRotationVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEd25519RecoverConstMeta =>
      const TaskConstMeta(
        debugName: "recover",
        argNames: [
          "sessionId",
          "round",
          "serverPayload",
          "backupShare",
          "currentRotationVersion",
        ],
      );

  @override
  Future<String> crateApiMpcEngineRecover({
    required String sessionId,
    required int round,
    required String serverPayload,
    String? backupShare,
    int? currentRotationVersion,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_i_32(round, serializer);
          sse_encode_String(serverPayload, serializer);
          sse_encode_opt_String(backupShare, serializer);
          sse_encode_opt_box_autoadd_i_32(currentRotationVersion, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMpcEngineRecoverConstMeta,
        argValues: [
          sessionId,
          round,
          serverPayload,
          backupShare,
          currentRotationVersion,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMpcEngineRecoverConstMeta => const TaskConstMeta(
    debugName: "recover",
    argNames: [
      "sessionId",
      "round",
      "serverPayload",
      "backupShare",
      "currentRotationVersion",
    ],
  );

  @override
  Future<(Curve, Uint8List)> crateApiTypesShareEnvelopeDecode({
    required String localEncryptedShare,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(localEncryptedShare, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_curve_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTypesShareEnvelopeDecodeConstMeta,
        argValues: [localEncryptedShare],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesShareEnvelopeDecodeConstMeta =>
      const TaskConstMeta(
        debugName: "share_envelope_decode",
        argNames: ["localEncryptedShare"],
      );

  @override
  Future<String> crateApiTypesShareEnvelopeEncode({
    required ShareEnvelope that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_share_envelope(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTypesShareEnvelopeEncodeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesShareEnvelopeEncodeConstMeta =>
      const TaskConstMeta(
        debugName: "share_envelope_encode",
        argNames: ["that"],
      );

  @override
  Future<ShareEnvelope> crateApiTypesShareEnvelopeNew({
    required Curve curve,
    required List<int> shareBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_curve(curve, serializer);
          sse_encode_list_prim_u_8_loose(shareBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_share_envelope,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesShareEnvelopeNewConstMeta,
        argValues: [curve, shareBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesShareEnvelopeNewConstMeta =>
      const TaskConstMeta(
        debugName: "share_envelope_new",
        argNames: ["curve", "shareBytes"],
      );

  @override
  Future<String> crateApiEngineEd25519Sign({
    required String sessionId,
    required int round,
    required String serverPayload,
    String? share,
    String? messageHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_i_32(round, serializer);
          sse_encode_String(serverPayload, serializer);
          sse_encode_opt_String(share, serializer);
          sse_encode_opt_String(messageHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEngineEd25519SignConstMeta,
        argValues: [sessionId, round, serverPayload, share, messageHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineEd25519SignConstMeta => const TaskConstMeta(
    debugName: "sign",
    argNames: ["sessionId", "round", "serverPayload", "share", "messageHex"],
  );

  @override
  Future<String> crateApiMpcEngineSign({
    required String sessionId,
    required int round,
    required String serverPayload,
    String? share,
    String? messageHashHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_i_32(round, serializer);
          sse_encode_String(serverPayload, serializer);
          sse_encode_opt_String(share, serializer);
          sse_encode_opt_String(messageHashHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMpcEngineSignConstMeta,
        argValues: [sessionId, round, serverPayload, share, messageHashHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMpcEngineSignConstMeta => const TaskConstMeta(
    debugName: "sign",
    argNames: [
      "sessionId",
      "round",
      "serverPayload",
      "share",
      "messageHashHex",
    ],
  );

  @override
  Future<Curve> crateApiTypesWireEnvelopeCurveOrDefault({
    required WireEnvelope that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_wire_envelope(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_curve,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesWireEnvelopeCurveOrDefaultConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesWireEnvelopeCurveOrDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "wire_envelope_curve_or_default",
        argNames: ["that"],
      );

  @override
  Future<List<Uint8List>> crateApiTypesWireEnvelopeDecodeAllPayloads({
    required WireEnvelope that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_wire_envelope(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTypesWireEnvelopeDecodeAllPayloadsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesWireEnvelopeDecodeAllPayloadsConstMeta =>
      const TaskConstMeta(
        debugName: "wire_envelope_decode_all_payloads",
        argNames: ["that"],
      );

  @override
  Future<WireEnvelope> crateApiTypesWireEnvelopeNew({
    required String sessionId,
    required ProtocolType protocol,
    required int round,
    required int fromId,
    int? toId,
    required String payload,
    String? step,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_protocol_type(protocol, serializer);
          sse_encode_u_8(round, serializer);
          sse_encode_u_8(fromId, serializer);
          sse_encode_opt_box_autoadd_u_8(toId, serializer);
          sse_encode_String(payload, serializer);
          sse_encode_opt_String(step, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wire_envelope,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesWireEnvelopeNewConstMeta,
        argValues: [sessionId, protocol, round, fromId, toId, payload, step],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesWireEnvelopeNewConstMeta =>
      const TaskConstMeta(
        debugName: "wire_envelope_new",
        argNames: [
          "sessionId",
          "protocol",
          "round",
          "fromId",
          "toId",
          "payload",
          "step",
        ],
      );

  @override
  Future<WireEnvelope> crateApiTypesWireEnvelopeNewBatch({
    required String sessionId,
    required ProtocolType protocol,
    required int round,
    required int fromId,
    int? toId,
    required List<String> payloads,
    String? step,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_protocol_type(protocol, serializer);
          sse_encode_u_8(round, serializer);
          sse_encode_u_8(fromId, serializer);
          sse_encode_opt_box_autoadd_u_8(toId, serializer);
          sse_encode_list_String(payloads, serializer);
          sse_encode_opt_String(step, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wire_envelope,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTypesWireEnvelopeNewBatchConstMeta,
        argValues: [sessionId, protocol, round, fromId, toId, payloads, step],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesWireEnvelopeNewBatchConstMeta =>
      const TaskConstMeta(
        debugName: "wire_envelope_new_batch",
        argNames: [
          "sessionId",
          "protocol",
          "round",
          "fromId",
          "toId",
          "payloads",
          "step",
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  DeserializeFrost dco_decode_TraitDef_DeserializeFrost(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  SerializeFrost dco_decode_TraitDef_SerializeFrost(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  MessageDigest dco_decode_box_autoadd_message_digest(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_message_digest(raw);
  }

  @protected
  ShareEnvelope dco_decode_box_autoadd_share_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_share_envelope(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  WireEnvelope dco_decode_box_autoadd_wire_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_wire_envelope(raw);
  }

  @protected
  Curve dco_decode_curve(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Curve.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessageDigest dco_decode_message_digest(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return MessageDigest(field0: dco_decode_u_8_array_32(arr[0]));
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  ProtocolType dco_decode_protocol_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProtocolType.values[raw as int];
  }

  @protected
  (Curve, Uint8List) dco_decode_record_curve_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_curve(arr[0]), dco_decode_list_prim_u_8_strict(arr[1]));
  }

  @protected
  ShareEnvelope dco_decode_share_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ShareEnvelope(
      v: dco_decode_u_8(arr[0]),
      curve: dco_decode_String(arr[1]),
      share: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array32(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WireEnvelope dco_decode_wire_envelope(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return WireEnvelope(
      sessionId: dco_decode_String(arr[0]),
      protocol: dco_decode_protocol_type(arr[1]),
      round: dco_decode_u_8(arr[2]),
      fromId: dco_decode_u_8(arr[3]),
      toId: dco_decode_opt_box_autoadd_u_8(arr[4]),
      payloadEncoding: dco_decode_String(arr[5]),
      payload: dco_decode_String(arr[6]),
      step: dco_decode_opt_String(arr[7]),
      payloads: dco_decode_opt_list_String(arr[8]),
      curve: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  MessageDigest sse_decode_box_autoadd_message_digest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_message_digest(deserializer));
  }

  @protected
  ShareEnvelope sse_decode_box_autoadd_share_envelope(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_share_envelope(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  WireEnvelope sse_decode_box_autoadd_wire_envelope(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_wire_envelope(deserializer));
  }

  @protected
  Curve sse_decode_curve(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Curve.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessageDigest sse_decode_message_digest(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_8_array_32(deserializer);
    return MessageDigest(field0: var_field0);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProtocolType sse_decode_protocol_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProtocolType.values[inner];
  }

  @protected
  (Curve, Uint8List) sse_decode_record_curve_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_curve(deserializer);
    var var_field1 = sse_decode_list_prim_u_8_strict(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  ShareEnvelope sse_decode_share_envelope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_v = sse_decode_u_8(deserializer);
    var var_curve = sse_decode_String(deserializer);
    var var_share = sse_decode_String(deserializer);
    return ShareEnvelope(v: var_v, curve: var_curve, share: var_share);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array32(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WireEnvelope sse_decode_wire_envelope(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_protocol = sse_decode_protocol_type(deserializer);
    var var_round = sse_decode_u_8(deserializer);
    var var_fromId = sse_decode_u_8(deserializer);
    var var_toId = sse_decode_opt_box_autoadd_u_8(deserializer);
    var var_payloadEncoding = sse_decode_String(deserializer);
    var var_payload = sse_decode_String(deserializer);
    var var_step = sse_decode_opt_String(deserializer);
    var var_payloads = sse_decode_opt_list_String(deserializer);
    var var_curve = sse_decode_opt_String(deserializer);
    return WireEnvelope(
      sessionId: var_sessionId,
      protocol: var_protocol,
      round: var_round,
      fromId: var_fromId,
      toId: var_toId,
      payloadEncoding: var_payloadEncoding,
      payload: var_payload,
      step: var_step,
      payloads: var_payloads,
      curve: var_curve,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_message_digest(
    MessageDigest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_message_digest(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_share_envelope(
    ShareEnvelope self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_share_envelope(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_wire_envelope(
    WireEnvelope self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wire_envelope(self, serializer);
  }

  @protected
  void sse_encode_curve(Curve self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_message_digest(MessageDigest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8_array_32(self.field0, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
    List<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_protocol_type(ProtocolType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_record_curve_list_prim_u_8_strict(
    (Curve, Uint8List) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_curve(self.$1, serializer);
    sse_encode_list_prim_u_8_strict(self.$2, serializer);
  }

  @protected
  void sse_encode_share_envelope(ShareEnvelope self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.v, serializer);
    sse_encode_String(self.curve, serializer);
    sse_encode_String(self.share, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wire_envelope(WireEnvelope self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_protocol_type(self.protocol, serializer);
    sse_encode_u_8(self.round, serializer);
    sse_encode_u_8(self.fromId, serializer);
    sse_encode_opt_box_autoadd_u_8(self.toId, serializer);
    sse_encode_String(self.payloadEncoding, serializer);
    sse_encode_String(self.payload, serializer);
    sse_encode_opt_String(self.step, serializer);
    sse_encode_opt_list_String(self.payloads, serializer);
    sse_encode_opt_String(self.curve, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
