// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_share_envelope`, `decode_payload`, `deser_pkg`, `encode_wire_payload`, `extract_share_material`, `keygen_finalize`, `keygen_round1`, `keygen_round2`, `make_completed`, `make_in_progress`, `parse_wire`, `ser_pkg`, `sign_round1`, `sign_round2`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DkgR1Payload`, `DkgR2Payload`, `Ed25519KeyMaterial`, `SignR1Payload`, `SignR2Payload`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `deserialize_frost`, `deserialize_frost`, `deserialize_frost`, `deserialize_frost`, `deserialize_frost`, `deserialize_frost`, `deserialize_frost`, `serialize_frost`, `serialize_frost`, `serialize_frost`, `serialize_frost`, `serialize_frost`, `serialize_frost`, `serialize_frost`

/// FROST DKG entry point. round semantics:
/// - 1: server's part1 round1_package arrives → client part1 → reply own round1_pkg
/// - 2: server's part2 round2_package arrives → client part2 → reply own round2_pkg
/// - 0: finalize (server signaled completion) → client part3 → return KeygenCompletedPayload
Future<String> keygen({
  required String sessionId,
  required int round,
  required String serverPayload,
}) => RustLib.instance.api.crateApiEngineEd25519Keygen(
  sessionId: sessionId,
  round: round,
  serverPayload: serverPayload,
);

/// FROST sign entry point. round semantics:
/// - 1: server's commitments arrive → client commit → reply own commitments
/// - 2: server's signing_pkg + sig_share arrive → client sig_share + aggregate
///      → return SignCompletedPayload (R || s, 64 bytes total)
Future<String> sign({
  required String sessionId,
  required int round,
  required String serverPayload,
  String? share,
  String? messageHex,
}) => RustLib.instance.api.crateApiEngineEd25519Sign(
  sessionId: sessionId,
  round: round,
  serverPayload: serverPayload,
  share: share,
  messageHex: messageHex,
);

abstract class DeserializeFrost {}

abstract class SerializeFrost {
  Future<Uint8List> serializeFrost();
}
