// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_cbor_base64`, `decrypt_share`, `derive_aes_key`, `encode_cbor_base64`, `encrypt_share`, `lagrange_coeff_2of2`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `KeyshareExportFields`

/// DKG 协议启动入口。
/// server_payload: 服务端 Round 1 WireEnvelope JSON（包含 KeygenMsg1）
/// 返回: MpcRoundResult JSON (status="in_progress", round=2, client_payload=WireEnvelope JSON)
Future<String> keygenStart({
  required String sessionId,
  required String serverPayload,
}) => RustLib.instance.api.crateApiMpcEngineKeygenStart(
  sessionId: sessionId,
  serverPayload: serverPayload,
);

/// DKG 协议轮次推进入口。
/// server_payload: 服务端当前轮次 WireEnvelope JSON
/// 返回: MpcRoundResult JSON（in_progress 或 completed）
Future<String> keygenContinue({
  required String sessionId,
  required String serverPayload,
}) => RustLib.instance.api.crateApiMpcEngineKeygenContinue(
  sessionId: sessionId,
  serverPayload: serverPayload,
);

Future<String> recoverStart({
  required String sessionId,
  required String backupShare,
  required String serverPayload,
  required int currentRotationVersion,
}) => RustLib.instance.api.crateApiMpcEngineRecoverStart(
  sessionId: sessionId,
  backupShare: backupShare,
  serverPayload: serverPayload,
  currentRotationVersion: currentRotationVersion,
);

Future<String> recoverContinue({
  required String sessionId,
  required String serverPayload,
}) => RustLib.instance.api.crateApiMpcEngineRecoverContinue(
  sessionId: sessionId,
  serverPayload: serverPayload,
);

/// DSG 协议启动入口。
/// share: JSON-serialized Keyshare（来自本地安全存储）
/// message_hash_hex: 32 字节消息摘要的 hex 编码（SEC-03 边界验证）
/// server_payload: 服务端 Round 1 WireEnvelope JSON（包含 SignMsg1）
/// 返回: MpcRoundResult JSON (status="in_progress", round=2, client_payload=WireEnvelope JSON)
Future<String> signStart({
  required String sessionId,
  required String share,
  required String messageHashHex,
  required String serverPayload,
}) => RustLib.instance.api.crateApiMpcEngineSignStart(
  sessionId: sessionId,
  share: share,
  messageHashHex: messageHashHex,
  serverPayload: serverPayload,
);

/// DSG 协议轮次推进入口。
/// server_payload: 服务端当前轮次 WireEnvelope JSON
/// 返回: MpcRoundResult JSON（in_progress 或 completed）
Future<String> signContinue({
  required String sessionId,
  required String serverPayload,
}) => RustLib.instance.api.crateApiMpcEngineSignContinue(
  sessionId: sessionId,
  serverPayload: serverPayload,
);

/// Derive a backup envelope from a live share and user secret.
/// Uses AES-256-GCM with HKDF-SHA256 key derivation.
Future<String> deriveBackupEnvelope({
  required String localEncryptedShare,
  required String userBackupSecret,
  required String createdAt,
}) => RustLib.instance.api.crateApiMpcEngineDeriveBackupEnvelope(
  localEncryptedShare: localEncryptedShare,
  userBackupSecret: userBackupSecret,
  createdAt: createdAt,
);

/// Decrypt a backup envelope to recover the device backup share.
Future<String> decryptBackupShare({
  required String encryptedEnvelope,
  required String userBackupSecret,
}) => RustLib.instance.api.crateApiMpcEngineDecryptBackupShare(
  encryptedEnvelope: encryptedEnvelope,
  userBackupSecret: userBackupSecret,
);

Future<String> exportPrivateKey({
  required String localShare,
  required String serverSharePrivate,
}) => RustLib.instance.api.crateApiMpcEngineExportPrivateKey(
  localShare: localShare,
  serverSharePrivate: serverSharePrivate,
);
