// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_all`, `decrypt_share_bytes`, `derive_aes_key`, `encrypt_share`, `extract_pubkey_and_address`, `inject_all`, `instance_id_from_session`, `make_completed`, `make_in_progress_batch`, `parse_server_envelope`, `random_seed`

/// DKG 协议统一入口。
/// round==0: 收集模式 — 不发消息，直接 join task 获取 Keyshare（用于服务端先完成的情况）
/// round==1: 创建 session
/// round>1: 推进已有 session
Future<String> keygen({
  required String sessionId,
  required int round,
  required String serverPayload,
}) => RustLib.instance.api.crateApiMpcEngineKeygen(
  sessionId: sessionId,
  round: round,
  serverPayload: serverPayload,
);

/// key_refresh 协议统一入口。round==1 需要 backup_share 和 current_rotation_version。
Future<String> recover({
  required String sessionId,
  required int round,
  required String serverPayload,
  String? backupShare,
  int? currentRotationVersion,
}) => RustLib.instance.api.crateApiMpcEngineRecover(
  sessionId: sessionId,
  round: round,
  serverPayload: serverPayload,
  backupShare: backupShare,
  currentRotationVersion: currentRotationVersion,
);

/// DSG 协议统一入口。round==1 需要 share 和 message_hash_hex。
Future<String> sign({
  required String sessionId,
  required int round,
  required String serverPayload,
  String? share,
  String? messageHashHex,
}) => RustLib.instance.api.crateApiMpcEngineSign(
  sessionId: sessionId,
  round: round,
  serverPayload: serverPayload,
  share: share,
  messageHashHex: messageHashHex,
);

Future<String> deriveBackupEnvelope({
  required String localEncryptedShare,
  required String userBackupSecret,
  required String createdAt,
}) => RustLib.instance.api.crateApiMpcEngineDeriveBackupEnvelope(
  localEncryptedShare: localEncryptedShare,
  userBackupSecret: userBackupSecret,
  createdAt: createdAt,
);

Future<String> decryptBackupShare({
  required String encryptedEnvelope,
  required String userBackupSecret,
}) => RustLib.instance.api.crateApiMpcEngineDecryptBackupShare(
  encryptedEnvelope: encryptedEnvelope,
  userBackupSecret: userBackupSecret,
);

Future<String> exportPrivateKey({
  required String localShare,
  required String serverSharePrivate,
}) => RustLib.instance.api.crateApiMpcEngineExportPrivateKey(
  localShare: localShare,
  serverSharePrivate: serverSharePrivate,
);
