// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            /// Remove a keygen session (cleanup after completion or timeout).
Future<KeygenSession?>  removeKeygenSession({required String sessionId }) => RustLib.instance.api.crateApiSessionRemoveKeygenSession(sessionId: sessionId);

/// Remove a recovery session.
Future<RecoverySession?>  removeRecoverySession({required String sessionId }) => RustLib.instance.api.crateApiSessionRemoveRecoverySession(sessionId: sessionId);

Future<SignSession?>  removeSignSession({required String sessionId }) => RustLib.instance.api.crateApiSessionRemoveSignSession(sessionId: sessionId);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< EcKeyPair>>
                abstract class EcKeyPair implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< EcKeyPair < GE >>>
                abstract class EcKeyPairGe implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< EphCommWitness>>
                abstract class EphCommWitness implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< EphEcKeyPair>>
                abstract class EphEcKeyPair implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< EphKeyGenFirstMsg>>
                abstract class EphKeyGenFirstMsg implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< KeyGenFirstMsg>>
                abstract class KeyGenFirstMsg implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KeygenSession>>
                abstract class KeygenSession implements RustOpaqueInterface {
                     EcKeyPairGe get ccEcKeyPair;


 Party1FirstMessage get ccPartyOneFirstMessage;


 EcKeyPair get ecKeyPair;


 KeyGenFirstMsg get kgPartyOneFirstMessage;


  set ccEcKeyPair(EcKeyPairGe ccEcKeyPair);


  set ccPartyOneFirstMessage(Party1FirstMessage ccPartyOneFirstMessage);


  set ecKeyPair(EcKeyPair ecKeyPair);


  set kgPartyOneFirstMessage(KeyGenFirstMsg kgPartyOneFirstMessage);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MasterKey2>>
                abstract class MasterKey2 implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Party1FirstMessage>>
                abstract class Party1FirstMessage implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Party1FirstMessage < GE >>>
                abstract class Party1FirstMessageGe implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Party2FirstMessage < GE >>>
                abstract class Party2FirstMessageGe implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecoverySession>>
                abstract class RecoverySession implements RustOpaqueInterface {
                     Party1FirstMessageGe get coinFlipParty1FirstMessage;


 Party2FirstMessageGe get coinFlipParty2FirstMessage;


 MasterKey2 get masterKey;


 int get rotationVersion;


  set coinFlipParty1FirstMessage(Party1FirstMessageGe coinFlipParty1FirstMessage);


  set coinFlipParty2FirstMessage(Party2FirstMessageGe coinFlipParty2FirstMessage);


  set masterKey(MasterKey2 masterKey);


  set rotationVersion(int rotationVersion);



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SignSession>>
                abstract class SignSession implements RustOpaqueInterface {
                     EphCommWitness get ephCommWitness;


 EphEcKeyPair get ephEcKeyPair;


 EphKeyGenFirstMsg get ephParty1FirstMessage;


 MasterKey2 get masterKey;


 String get messageHash;


  set ephCommWitness(EphCommWitness ephCommWitness);


  set ephEcKeyPair(EphEcKeyPair ephEcKeyPair);


  set ephParty1FirstMessage(EphKeyGenFirstMsg ephParty1FirstMessage);


  set masterKey(MasterKey2 masterKey);


  set messageHash(String messageHash);



                    
                }
                
            