// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BackupEnvelope`, `DecryptBackupResult`, `ExportResult`, `KeygenCompletedPayload`, `MpcRoundResult`, `RecoveryCompletedPayload`, `SignCompletedPayload`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 32 字节消息摘要的安全类型包装。
/// 防止将任意 Vec<u8> 直接传入签名函数。
/// 不实现 From<Vec<u8>>、From<&[u8]> 或 From<[u8; 32]>。
class MessageDigest {
  final U8Array32 field0;

  const MessageDigest({required this.field0});

  /// 引用底层字节。
  Future<void> asBytes() =>
      RustLib.instance.api.crateApiTypesMessageDigestAsBytes(that: this);

  /// 从 hex string 构造（FRB Dart 侧传入路径）。
  static Future<MessageDigest> fromHex({required String s}) =>
      RustLib.instance.api.crateApiTypesMessageDigestFromHex(s: s);

  /// 获取底层字节（传给 dkls23-ll create_partial_signature）。
  Future<U8Array32> intoBytes() =>
      RustLib.instance.api.crateApiTypesMessageDigestIntoBytes(that: this);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 从精确的 32 字节数组构造。
  static Future<MessageDigest> newInstance({required U8Array32 bytes}) =>
      RustLib.instance.api.crateApiTypesMessageDigestNew(bytes: bytes);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDigest &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

/// 协议类型枚举，用于 wire format 信封路由。
enum ProtocolType { dkg, dsg, rotation }

/// client ↔ server 协议消息的统一 JSON 信封。
/// dkls23-ll 消息通过 serde 序列化后放入 payload 字段。
/// 此结构在 Phase 8 冻结，Phase 9-13 直接使用。
class WireEnvelope {
  /// 32 字节 session ID 的 hex 编码
  final String sessionId;

  /// 协议类型
  final ProtocolType protocol;

  /// 轮次编号 (1-4)
  final int round;

  /// 发送方 party ID
  final int fromId;

  /// 接收方 party ID（None = broadcast）
  final int? toId;

  /// payload 编码方式（默认 "cbor_base64"）
  final String payloadEncoding;

  /// 单条消息（Base64 编码）— 向后兼容
  final String payload;

  /// 批量消息（Base64 编码数组）— 优先使用，减少 HTTP 往返
  final List<String>? payloads;

  /// 可选步骤标识
  final String? step;

  const WireEnvelope({
    required this.sessionId,
    required this.protocol,
    required this.round,
    required this.fromId,
    this.toId,
    required this.payloadEncoding,
    required this.payload,
    this.payloads,
    this.step,
  });

  /// 提取所有 payload bytes（兼容单条和批量）
  Future<List<Uint8List>> decodeAllPayloads() => RustLib.instance.api
      .crateApiTypesWireEnvelopeDecodeAllPayloads(that: this);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 构造新信封，payload_encoding 默认为 "cbor_base64"
  static Future<WireEnvelope> newInstance({
    required String sessionId,
    required ProtocolType protocol,
    required int round,
    required int fromId,
    int? toId,
    required String payload,
    String? step,
  }) => RustLib.instance.api.crateApiTypesWireEnvelopeNew(
    sessionId: sessionId,
    protocol: protocol,
    round: round,
    fromId: fromId,
    toId: toId,
    payload: payload,
    step: step,
  );

  /// 批量消息构造 — 多条 Base64 payload 打包
  static Future<WireEnvelope> newBatch({
    required String sessionId,
    required ProtocolType protocol,
    required int round,
    required int fromId,
    int? toId,
    required List<String> payloads,
  }) => RustLib.instance.api.crateApiTypesWireEnvelopeNewBatch(
    sessionId: sessionId,
    protocol: protocol,
    round: round,
    fromId: fromId,
    toId: toId,
    payloads: payloads,
  );

  @override
  int get hashCode =>
      sessionId.hashCode ^
      protocol.hashCode ^
      round.hashCode ^
      fromId.hashCode ^
      toId.hashCode ^
      payloadEncoding.hashCode ^
      payload.hashCode ^
      payloads.hashCode ^
      step.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WireEnvelope &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          protocol == other.protocol &&
          round == other.round &&
          fromId == other.fromId &&
          toId == other.toId &&
          payloadEncoding == other.payloadEncoding &&
          payload == other.payload &&
          payloads == other.payloads &&
          step == other.step;
}
